[target.aarch64-unknown-linux-gnu]
  zig = "2.31" # Target specific 'GLIBC' using 'zig cc' as a cross-compiler.
[target.x86_64-unknown-linux-gnu]
  zig = "2.31" # Target specific 'GLIBC' using 'zig cc' as a cross-compiler.
