//! Generated code for package `test.collections`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub struct Container {
    pub numbers: Vec<u32>,
    pub names: Vec<String>,
    pub fixed_size: Vec<u32>,
    pub counts: HashMap<String, u32>,
    pub reverse: HashMap<u32, String>,
}

impl Container {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            numbers: Vec::new(),
            names: Vec::new(),
            fixed_size: Vec::new(),
            counts: HashMap::new(),
            reverse: HashMap::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut impl Write) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &mut impl Read) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Container {
    fn default() -> Self {
        Self::new()
    }
}

