//! Generated code for package `test.docs`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

/// Account status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    /// Not yet activated.
    Pending,
    /// Active and in good standing.
    Active,
}

#[derive(Debug, Clone, PartialEq)]
pub struct User {
    /// The unique identifier.
    pub id: u32,
    /// The user's display name.
    pub name: String,
}

impl User {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            id: 0,
            name: String::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut impl Write) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &mut impl Read) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new()
    }
}

