//! Generated code for package `test.encoded`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub struct Encoded {
    pub compact: u32,
    pub signed_compact: i32,
    pub variable: u64,
    pub delta_encoded: i32,
    pub fixed_val: f32,
    pub padded: u32,
}

impl Encoded {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            compact: 0,
            signed_compact: 0,
            variable: 0,
            delta_encoded: 0,
            fixed_val: 0.0,
            padded: 0,
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut impl Write) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &mut impl Read) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Encoded {
    fn default() -> Self {
        Self::new()
    }
}

