//! Generated code for package `test.types`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub struct Scalars {
    pub flag: bool,
    pub tiny: u8,
    pub small: u16,
    pub medium: u32,
    pub large: u64,
    pub signed_tiny: i8,
    pub signed_small: i16,
    pub signed_medium: i32,
    pub signed_large: i64,
    pub float_val: f32,
    pub double_val: f64,
    pub text: String,
    pub single_byte: u8,
    pub flag_bit: bool,
}

impl Scalars {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            flag: false,
            tiny: 0,
            small: 0,
            medium: 0,
            large: 0,
            signed_tiny: 0,
            signed_small: 0,
            signed_medium: 0,
            signed_large: 0,
            float_val: 0.0,
            double_val: 0.0,
            text: String::new(),
            single_byte: 0,
            flag_bit: false,
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut impl Write) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &mut impl Read) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Scalars {
    fn default() -> Self {
        Self::new()
    }
}

