//! Generated code for package `test.multi`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

use crate::test::multi;
#[derive(Debug, Clone, PartialEq)]
pub struct User {
    pub id: u32,
    pub name: String,
}

impl User {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            id: 0,
            name: String::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for User {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Post {
    pub id: u32,
    pub author: User,
    pub content: String,
}

impl Post {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            id: 0,
            author: User::new(),
            content: String::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Post {
    fn default() -> Self {
        Self::new()
    }
}

