//! Generated code for package `test.empty`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub struct Empty {
}

impl Empty {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Empty {
    fn default() -> Self {
        Self::new()
    }
}

