//! Generated code for package `test.status`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

use crate::test::status;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    Unknown,
    Active,
    Inactive,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tagged {
    None,
    Number(u32),
    Text(String),
}

#[derive(Debug, Clone, PartialEq)]
pub struct WithEnum {
    pub status: Status,
    pub status: Status,
    pub value: Tagged,
    pub value: Tagged,
}

impl WithEnum {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            status: Status::default(),
            status: Status::default(),
            value: Tagged::default(),
            value: Tagged::default(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for WithEnum {
    fn default() -> Self {
        Self::new()
    }
}

