//! Generated code for package `test.merge`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

#[derive(Debug, Clone, PartialEq)]
pub struct First {
    pub id: u32,
}

impl First {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            id: 0,
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for First {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Second {
    pub name: String,
}

impl Second {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            name: String::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Second {
    fn default() -> Self {
        Self::new()
    }
}

