//! Generated code for package `test.nesting`.
//!
//! This file was automatically generated by baproto.
//! Do not edit manually.

use std::collections::HashMap;
use std::io::{Read, Write};

use crate::test::nesting;
#[derive(Debug, Clone, PartialEq)]
pub struct Level3 {
    pub active: bool,
}

impl Level3 {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            active: false,
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Level3 {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Level2 {
    pub name: String,
    pub deepest: Level3,
}

impl Level2 {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            name: String::new(),
            deepest: Level3::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Level2 {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Level1 {
    pub id: u32,
    pub nested: Level2,
}

impl Level1 {
    /// Creates a new instance with default values.
    pub fn new() -> Self {
        Self {
            id: 0,
            nested: Level2::new(),
        }
    }

    /// Encodes this message to a writer.
    pub fn encode(&self, _writer: &mut [u8]) -> std::io::Result<()> {
        todo!("serialization not yet implemented")
    }

    /// Decodes a message from a reader.
    pub fn decode(_reader: &[u8]) -> std::io::Result<Self> {
        todo!("deserialization not yet implemented")
    }
}

impl Default for Level1 {
    fn default() -> Self {
        Self::new()
    }
}

